### ISSUE TITLE
Implement backend logic to suggest valid cycle/pass/scene to end user and validate the cycle/pass/scene inputs

### ISSUE THREAD

**Issue by viviant100** [podaac/swodlr#71]
Build a microservice that receives the CNM messages from IA and perform analysis on the CNM messages in order to provide valid cycle/pass/scene for the users (3sp)
- Attach a new SQS queue to I&A SNS topic for the CNM messages.

Pre-verification for client-side to validate the input (2sp),

**Comment by joshgarde** [comment]
The suggestion feature as currently proposed does not seem reasonable to implement as currently proposed. The current state of this feature proposes that:
- when nothing is provided, a list of valid cycles is returned
- when a cycle is provided, a list of valid passes is returned
- when a cycle + pass is provided, a list of valid scenes is returned

For context: each variable in the search is dependent on the variable before it. If a list of valid passes and scenes is generated from a cycle, the combination of both the pass + scene as a pair must be utilized together to form a valid CPS combo.

The SWOT satellite is expected to generate a lot of PIXC/PIXCVec tiles which are used to generate scenes when combined together. As a result, valid combinations generated could potentially reach the hundreds/thousands on each variable. In order to support this functionality, we would need to build out a process within ingest-to-sds which generates search indices for each of these parameters for the API to utilize.

For example:
- an index entry of `(null,null,null) -> [list of valid cycles]`
- an index entry of `(123,null,null) -> [list of valid passes]`
- an index entry of `(123,123,null) -> [list of valid scenes]`

Each of these indices would need to be updated as a granule is ingested through the SDS. Performing this work would be fairly non-trivial for a feature that doesn't seem like it would be useful once Earthdata Search integration is implemented.

**Comment by joshgarde** [comment]
PRs open - in-review

- https://github.com/podaac/swodlr-ingest-to-sds/pull/9
- https://github.com/podaac/swodlr-api/pull/16

**Comment by joshgarde** [comment]
Hotfix created:

https://github.com/podaac/swodlr-ingest-to-sds/pull/11

**Comment by joshgarde** [comment]
Merged
