### ISSUE TITLE
How can I run this API in my locale?

### ISSUE THREAD

**Issue by yessGlory17** [podaac/swodlr#99]
How can I run this API in my locale? I need some documentation.
[https://github.com/podaac/swodlr-api/tree/develop](https://github.com/podaac/swodlr-api/tree/develop)

**Comment by joshgarde** [comment]
Hello - we don't currently have formal documentation for running swodlr-api locally because a lot of its functionality relies on having access to application credentials from Earthdata Login which is our OAuth2 provider - https://urs.earthdata.nasa.gov/. Unfortunately, I do not believe that they currently offer external users the ability to create their own application credentials which limits the functionality of swodlr-api for local use.

Alternatively, swodlr-ui can be run locally and run against our publicly accessible API. You would just need to clone the swodlr-ui repo and create a .env file copying the contents of our UAT deployment variables.

```
REACT_APP_SWODLR_API_BASE_URI = https://swodlr.podaac.uat.earthdatacloud.nasa.gov/api
REACT_APP_BASE_REDIRECT_URI = http://localhost:3000/
REACT_APP_EDL_CLIENT_ID = n0oQvwh7W8Y1d7GVtNsFsQ
REACT_APP_EDL_BASE_URI = https://swodlr.podaac.uat.earthdatacloud.nasa.gov/api/edl/
```

I believe that in order for this to work properly, some browser security settings such as CORS would need to be disabled for local testing.

**Comment by yessGlory17** [comment]
Thanks @joshgarde
